services:
    db:
        image: mysql:8.0-debian
        container_name: quincaillerie_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: dev
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
            MYSQL_DATABASE: quincaillerie_sekkar
        ports:
            - '3307:3306'
        volumes:
            - db_data:/var/lib/mysql
            - ./backup-from-idx.sql:/docker-entrypoint-initdb.d/backup-from-idx.sql:ro
    redis:
        image: redis:7.0-alpine
        container_name: quincaillerie_redis
        restart: unless-stopped
        ports:
            - '6379:6379'
volumes:
    db_data:
